version: '3'

services:
  bug-squashing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - COMPETITION_START_DATE=${COMPETITION_START_DATE}
      - COMPETITION_END_DATE=${COMPETITION_END_DATE}
      - POINTS_PER_BUG=${POINTS_PER_BUG}
      - BONUS_POINTS=${BONUS_POINTS}
    volumes:
      - bug-squashing-data:/data
    restart: unless-stopped

volumes:
  bug-squashing-data: